#!/bin/bash

echo "First task"
# Создание директории и файле в ней 
mkdir DIR
touch DIR/Myfile.txt
echo "File created"
# Запись фамилии и даты в файл(date +%r обозначает запись только времени)
echo "Luchitz" > DIR/Myfile.txt
date +%r >> DIR/Myfile.txt
echo "Complete!"

echo "Second task"

# Подсчет общего количества аргументов
echo "Общее количество аргументов: $ #"

# Чтение значений аргументов по отдельности
echo "Значение первого аргумента: $1"
echo "Значение второго аргумента: $2"
echo "Значение третьего аргумента: $3"

# Чтение значений аргументов с использованием цикла
for argval in "$@"
do
echo -n "$argval "
done

# Добавление значений аргументов
sum=$(($1+$2+$3))

# Вывод результата
echo -e "\nРезультат суммы = $sum"

echo "Third task"	
# Использование встроенной в оболочку интерпретации bash
echo $((2#1101))

echo "Fourth task"
avr=$((($1+$2+$3)/3)) 
echo -e "\nСреднее = $avr"

echo "Fifth task"
echo -n "Enter the name: "
read
if [ "$REPLY" == "$USER" ]; then
echo yes
else
echo no
 fi
 
echo "Sixth task"
for (( i=0; i < 2; i++ )); do
                if [[ $1 -lt $2 ]]; then
                        shift
                else
                        set $1 $3
                fi
        done
        echo $1
        
 echo "Seventh task"
 
 read n
 read m
 read t
 
 if (($n == $m && $m == $t && $n==$t))
 then 
 echo "equilateral" 
 elif (($n==$m || $m==$t || $n==$t))
 then
 echo "isosceles"
 else 
 echo "versatile"
 fi
 
  echo "Eighth task"
  
echo "Enter Size(N)"
read N

i=1
sum=0

echo "Enter Numbers"
while [ $i -le $N ]
do
  read num               #get number
  sum=$((sum + num))     #sum+=num
  i=$((i + 1))
done

avg=$(echo $sum / $N | bc -l)

echo $avg
  
 echo "Ninth task"
 
 read s
 
  for n in $(seq 1 $s)  # generate 1,2,3 .. s
do 
 SQ=$(($n * $n)) 
 echo "SQ $SQ" 
done 

echo "Ten task"

echo "Enter a number"
read num

sum=0

while [ $num -gt 0 ]
do
    mod=$((num % 10))    #It will split each digits
    sum=$((sum + mod))   #Add each digit to sum
    num=$((num / 10))    #divide num by 10.
done

echo $sum
 
 

